# Generated by Django 4.2.1 on 2023-09-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_accountprofile_userid'),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendships',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='status',
        ),
        migrations.AddField(
            model_name='friendships',
            name='friend',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='users.account'),
        ),
        migrations.AddField(
            model_name='friendships',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.account'),
        ),
    ]
