# Generated by Django 4.2.1 on 2023-12-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_classroom_remove_account_department_and_more'),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.account')),
            ],
        ),
    ]
