# Generated by Django 4.2.1 on 2023-09-17 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_accountprofile_userid'),
        ('friendships', '0002_remove_friendships_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFriendShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.account')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='users.account')),
            ],
        ),
    ]
