# Generated by Django 4.2.1 on 2023-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0003_requestfriendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfriendship',
            name='status',
        ),
        migrations.AddField(
            model_name='requestfriendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
