# Generated by Django 4.2.1 on 2023-09-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_birthday_account_birthday_and_more'),
        ('friendships', '0005_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='list_friends', to='users.account')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='users.account')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.account')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='users.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestfriendship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='requestfriendship',
            name='requester',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='FriendShips',
        ),
        migrations.DeleteModel(
            name='RequestFriendShip',
        ),
    ]
