# Generated by Django 4.2.1 on 2023-09-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_birthday_account_birthday_and_more'),
        ('friendships', '0006_friends_request_remove_friendships_friend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='userid',
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_friend', to='users.account'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_of', to='users.account'),
        ),
    ]
