# Generated by Django 4.2.1 on 2023-09-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_birthday_account_birthday_and_more'),
        ('friendships', '0007_remove_friends_userid_friends_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friends_of', to='users.account'),
        ),
    ]
