# Generated by Django 4.2.1 on 2023-09-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0008_alter_friends_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accepted',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
