# Generated by Django 4.2.1 on 2023-09-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_account_friends'),
        ('friendships', '0010_remove_friends_friends_friends_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friends',
        ),
        migrations.AddField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friends_of', to='users.account'),
        ),
    ]
