# Generated by Django 4.2.1 on 2023-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_account_friends'),
        ('friendships', '0011_remove_friends_friends_friends_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_of', to='users.account'),
        ),
    ]
