# Generated by Django 4.2.1 on 2023-11-27 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(default='NORMAL', max_length=100)),
                ('birthday', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('OTHER', 'OTHER')], max_length=10, null=True)),
                ('department', models.CharField(default=None, max_length=100, null=True)),
                ('classroom', models.CharField(default=None, max_length=100, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
