# Generated by Django 4.2.1 on 2023-09-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountprofile',
            old_name='user',
            new_name='userID',
        ),
    ]
