# Generated by Django 4.2.1 on 2023-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_accountprofile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_of', to='users.account'),
        ),
    ]
