# Generated by Django 4.2.1 on 2023-09-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_createdat_account_updateat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userBirthDay',
            field=models.CharField(max_length=200),
        ),
    ]
