# Generated by Django 4.2.1 on 2023-09-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_account_userbirthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userGender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='account',
            name='userRole',
        ),
        migrations.AddField(
            model_name='account',
            name='userRole',
            field=models.CharField(default='NORMAL', max_length=100),
        ),
    ]
