# Generated by Django 4.2.1 on 2023-09-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_account_usergender_remove_account_userrole_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userBirthDay',
            new_name='BirthDay',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userGender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userName',
            new_name='PassWord',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userRole',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userPassWord',
            new_name='name',
        ),
    ]
