# Generated by Django 4.2.1 on 2023-09-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_userbirthday_account_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='BirthDay',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='PassWord',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Role',
            new_name='role',
        ),
    ]
