# Generated by Django 4.2.1 on 2023-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_birthday_account_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(related_name='friends_of', to='users.account'),
        ),
    ]
