# Generated by Django 4.2.1 on 2023-09-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_account_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friends_of', to='users.account'),
        ),
    ]
