# Generated by Django 4.2.1 on 2023-09-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_account_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
    ]
