# Generated by Django 4.2.1 on 2023-09-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_account_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='username',
        ),
    ]
