# Generated by Django 4.2.1 on 2023-09-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_name_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
    ]
