# Generated by Django 4.2.1 on 2023-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_account_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='updateAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
