version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: tdmu-postgres
    environment:
      POSTGRES_DB: user-service-db        
      POSTGRES_USER: user-service         
      POSTGRES_PASSWORD: abc536@#b 
    ports:
      - "5432:5432"    
    networks:
      - tdmu-network            

  app:
    image: mintrees/mintreestdmu:tagname   
    container_name: user-service-container
    environment:
      DATABASE_URL: postgres://user-service:abc536@#b@172.22.0.2:5432/user-service-db
      ALLOWED_HOSTS: "*"
    depends_on:
      - postgres
    networks:
      - tdmu-network 

  tdmu-user-service:
    image: mintrees/mintreestdmu:tagname
    container_name: tdmu-user-service
    ports:
      - "${DJANGO_PORT}:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      CORS_ALLOWED_ORIGINS: "*"
      DJANGO_PORT: ${DJANGO_PORT:-8090}
    networks:
      - tdmu-social
      - tdmu-network
    
networks:
  tdmu-social:
    external: true
  tdmu-network:
    external: true