version: '3.10.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: user:latest
    restart: always
    environment:
      POSTGRES_DB: raiway
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : ZmsQVysqLScgGCQ6WVfd'
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 7805:7805

